context:
  version: "0.3.0"

package:
  name: gwframe
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/g/gwframe/gwframe-${{ version }}.tar.gz
  sha256: 200009766d2d7195a6475a08c4b77ff6ae84a3643eaf2b3a4f3945a2bfff924b

build:
  skip:
    - win
  script: build.sh
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ stdlib('c') }}
    - cmake >=3.15
    - make
    - pkg-config
    - if: build_platform != target_platform
      then:
        - cross-python_${{ target_platform }}
        - python
  host:
    - nanobind >=2.0.0
    - pip
    - python
    - scikit-build-core >=0.10
    - setuptools-scm >=8.0
    - ldas-tools-framecpp
    - libboost-headers
  run:
    - numpy >=1.26
    - python
    - rich >=13.0.0
    - typer >=0.20.0

tests:
  - python:
      imports:
        - gwframe
        - gwframe.read
        - gwframe.write
        - gwframe.types
      pip_check: true
  - script:
      - gwframe --help

about:
  homepage: https://git.ligo.org/olivia.godwin/gwframe
  summary: High-level Python library to work with gravitational-wave frame (GWF) files
  description: |
    gwframe is a high-level Python library for reading and writing
    gravitational-wave frame (GWF) files, built on top of frameCPP.
  license: GPL-2.0-or-later
  license_file: LICENSE
  documentation: https://git.ligo.org/olivia.godwin/gwframe
  repository: https://git.ligo.org/olivia.godwin/gwframe

extra:
  recipe-maintainers:
    - nothisisolivia
